### ISSUE TITLE
error on running region_analysis

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lishen/diffreps#2]
```
What steps will reproduce the problem?
1. see example command below
2. file test.loc is a head of a file containing only three columns (chom, 
start, end)
3. mm10 was downloaded from Dropbox and installed as directed

What is the expected output? What do you see instead?

[rhart@localhost mouse]$ region_analysis.py -i test.loc -r -g mm10
refseq database version mm10 of mm10, RAver 3.00 will be used.
Traceback (most recent call last):
  File "/usr/bin/region_analysis.py", line 7, in <module>
    execfile(__file__)
  File "/home/rhart/Documents/region_analysis/bin/region_analysis.py", line 164, in <module>
    main()
  File "/home/rhart/Documents/region_analysis/bin/region_analysis.py", line 118, in main
    input_GB = input_bed_mid.intersect(anno, wao=True).saveas()
  File "/home/rhart/Documents/pybedtools/pybedtools/bedtool.py", line 668, in decorated
    result = method(self, *args, **kwargs)
  File "/home/rhart/Documents/pybedtools/pybedtools/bedtool.py", line 243, in wrapped
    check_stderr=check_stderr)
  File "/home/rhart/Documents/pybedtools/pybedtools/helpers.py", line 440, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

        bedtools intersect -wao -b /home/rhart/Documents/mouse/pybedtools.9pGU9n.tmp -a /home/rhart/Documents/mouse/pybedtools.W0SOG_.tmp

Error message was:
***** ERROR: illegal character '+' found in integer conversion of string +. 
Exiting...

[rhart@localhost mouse]$

What version of the product are you using? On what operating system?
0.1.2 on Fedora 19

Please provide any additional information below.

```

Original issue reported on code.google.com by `rhart...@gmail.com` on 16 Dec 2014 at 8:55

**Comment by ny-shao** [comment]
This issue is wired, like some problems of pybedtools. Would you like to try the newest version of pybedtools?
For the test bed, it works fine on my desktop, based on newest pybedtools.

**Comment by eddielohyh** [comment]
I encountered this exact same issue recently. After some tracking, I found that the problem wasn't with region_analysis nor pybedtools, but with bedtools itself. My latest bedtools v2.23.0 caused the error but works perfectly fine when my path points to another older bedtools v2.17.0 that I have. Try rolling back your bedtools to an earlier version.
